name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5

      - name: Install dependencies
        run: bundle install --path ./pg-core/

      - name: Build Docker image
        run: docker build -t pg-core .

      - name: Push Docker image to registry
        run: docker push pg-core

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: ssh-action/ssh-action@v2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production
        run: ssh -t <span class="math-inline">\{\{ secrets\.REMOTE\_USER \}\}@</span>{{ secrets.REMOTE_HOST }} "docker run -d -p 3000:3000 -p 5432:5432 pg-core"
